name: Unzip src-tauri.zip and Commit

on:
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to push changes

      - name: Unzip src-tauri.zip
        run: |
          cd tauri-app
          unzip -o src-tauri.zip -d src-tauri-unzipped

      - name: Move unzipped files
        run: |
          rm -rf tauri-app/src-tauri
          mv tauri-app/src-tauri-unzipped tauri-app/src-tauri

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tauri-app/src-tauri
          git commit -m "Unzipped src-tauri.zip via GitHub Actions" || echo "No changes to commit"
          git push
